# Sorts `Cargo.toml` dependencies. All other `.toml` files are formatted with the default config.
#
# https://taplo.tamasfe.dev/configuration/file.html#configuration-file

include = ["Cargo.toml", "deny.toml", "taplo.toml", ".cargo/audit.toml"]
exclude = [".direnv/**", "target/**"]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies"]

[rule.formatting]
reorder_keys = true
